# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceGen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('mode', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=20)),
            ],
        ),
    ]
