# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceGen', '0005_auto_20160827_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='sentence',
            field=models.CharField(max_length=2000),
        ),
    ]
