# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceGen', '0007_question_wordpks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='old_questions',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='sentence',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='wordPKs',
            field=models.CharField(max_length=200),
        ),
    ]
